baseURL = "https://imroc.io/"
languageCode = "zh-cn"
title = "roc"
theme = "beautifulhugo"
DefaultContentLanguage = "en"
hasCJKLanguage = true
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
#googleAnalytics = "XXX"


[Params]
  hello = "Hi,I'm Roc"
  # subtitle = "I'm ROC"
  logo = "images/logo.png"
  favicon = "favicon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  algolia = "6a65fd1d25daa9b3ba8ae02715023e72" # API key

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "docker"
    url = "categories/docker"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "golang"
    url = "categories/golang"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "架构"
    url = "categories/arch"
    weight = 3

[[menu.main]]
    name = "Books"
    weight = 2

[[menu.main]]
    parent = "Books"
    name = "Kubernetes The Gradual Way"
    url = "kubernetes-the-gradual-way"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "About"
    url = "about"
    weight = 4


[Author]
  name = "roc"
  website = "imroc.io"
  email = "roc@imroc.io"
  github = "imroc"
  twitter = "imrocchan"
  # facebook = "username"
  # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  # gitlab = "username"
  # reddit = "username"
  # linkedin = "username"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # telegram = "username"
