baseURL = "http://imroc.io/"
# languageCode = "zh-CN"
title = "roc"
theme = "beautifulhugo"

[Params]
  subtitle = "I'm ROC"
  logo = "images/logo.png"
  favicon = "favicon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2

[[menu.main]]
    name = "About"
    url = "about"
    weight = 3


[Author]
  name = "roc"
  website = "imroc.io"
  email = "roc@imroc.io"
  github = "imroc"
  twitter = "imrocchan"
  # facebook = "username"
  # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  # gitlab = "username"
  # reddit = "username"
  # linkedin = "username"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # telegram = "username"
