---
baseurl: "https://imroc.io/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "roc" 
theme: "beautifulhugo"
metaDataFormat: "yaml"
dateFormat: "January 2, 2006"
algolia:
  index: "roc"
  key: "6a65fd1d25daa9b3ba8ae02715023e72"
  appID: "VX13HR2WNF"
---

